### ISSUE TITLE
data from firmware 2.6.1 - IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by tcj** [sofarocean/spotter-sd-parser#22]
```
% python3 ~/src/spotter-sd-parser/sd_file_parser.py 
Concatenating all FLT files:
- 0006_FLT.csv (File 1 out of 1)
Processing Spotter displacement output - FLT
- IIR phase correction using weight type:  0
Concatenating all SPC files:
- 0006_SPC.csv (File 1 out of 1)
Processing Spotter spectral output
Concatenating all SYS files:
- 0006_SYS.log (File 1 out of 1)
Concatenating all LOC files:
- 0006_LOC.csv (File 1 out of 1)
Processing Spotter displacement output - LOC
Concatenating all GPS files:
- 0006_GPS.log (File 1 out of 1)
Concatenating all SST files:
- 0006_SST.csv (File 1 out of 1)
Processing Spotter displacement output - SST
Traceback (most recent call last):
  File "/Users/tcj/src/spotter-sd-parser/sd_file_parser.py", line 1740, in <module>
    main(**arguments)
  File "/Users/tcj/src/spotter-sd-parser/sd_file_parser.py", line 560, in main
    spectrum = Spectrum(path=outpath,outpath=outpath)
  File "/Users/tcj/src/spotter-sd-parser/sd_file_parser.py", line 230, in __init__
    self._load_parser_output()
  File "/Users/tcj/src/spotter-sd-parser/sd_file_parser.py", line 286, in _load_parser_output
    self.time = data[ : , 0:8 ]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by tcj** [comment]
https://github.com/sofarocean/spotter-sd-parser/pull/23
